# Generated by Django 5.2.6 on 2025-09-08 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='rewards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yuborilgan', 'Yuborilgan'), ('mahalla', 'Mahalla jarayonida'), ('tuman', 'Tuman'), ('hudud', 'Hudud'), ('oxirgi_tasdiqlash', 'Oxirgi tasdiqlash'), ('mukofotlangan', 'Mukofotlangan'), ('rad_etilgan', 'Rad etilgan')], default='yuborilgan', max_length=20)),
                ('area', models.CharField(choices=[('Andijon', 'Andijon viloyati'), ('Buxoro', 'Buxoro viloyati'), ('Fargona', 'Fargʻona viloyati'), ('Jizzax', 'Jizzax viloyati'), ('Namangan', 'Namangan viloyati'), ('Navoiy', 'Navoiy viloyati'), ('Qashqadaryo', 'Qashqadaryo viloyati'), ('Qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('Samarqand', 'Samarqand viloyati'), ('Sirdaryo', 'Sirdaryo viloyati'), ('Surxondaryo', 'Surxondaryo viloyati'), ('Toshkent', 'Toshkent viloyati'), ('Toshkent_shahri', 'Toshkent shahri'), ('Xorazm', 'Xorazm viloyati')], default='Andijon', max_length=20)),
                ('district', models.CharField(max_length=200, null=True)),
                ('neighborhood', models.CharField(max_length=200, null=True)),
                ('activity', models.CharField(max_length=200, null=True)),
                ('activity_description', models.TextField(null=True)),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='recommendation/')),
                ('source', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.reward')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificates',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['created_at'],
            },
        ),
    ]
