# Generated by Django 5.2.6 on 2025-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='area',
            field=models.CharField(choices=[('Andijon', 'Andijon viloyati'), ('Buxoro', 'Buxoro viloyati'), ('Fargona', 'Fargʻona viloyati'), ('Jizzax', 'Jizzax viloyati'), ('Namangan', 'Namangan viloyati'), ('Navoiy', 'Navoiy viloyati'), ('Qashqadaryo', 'Qashqadaryo viloyati'), ('Qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('Samarqand', 'Samarqand viloyati'), ('Sirdaryo', 'Sirdaryo viloyati'), ('Surxondaryo', 'Surxondaryo viloyati'), ('Toshkent', 'Toshkent viloyati'), ('Toshkent_shahri', 'Toshkent shahri'), ('Xorazm', 'Xorazm viloyati')], max_length=20),
        ),
    ]
