# Generated by Django 5.2.6 on 2025-09-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
