# Generated by Django 5.2.6 on 2025-09-05 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='verification_type',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('login', 'Login Verification'), ('reset', 'Password Reset')], default='signup', max_length=20),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
