# Generated by Django 5.2.6 on 2025-09-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
