# Generated by Django 5.2.6 on 2025-09-08 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='working_place',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passport_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pinfl',
            field=models.CharField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
    ]
