# Generated by Django 5.2.6 on 2025-09-10 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('application_crated', 'Application Created'), ('application_updated', 'Application Updated'), ('application_rejected', 'Application Rejected'), ('reward_won', 'Reward Won')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='sent', max_length=10)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
